"""Add DependentProfile table and birthdate column

Revision ID: 42706df5ad40
Revises: b008d3b1b6dd
Create Date: 2026-02-25 04:02:17.104633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42706df5ad40'
down_revision: Union[str, Sequence[str], None] = 'b008d3b1b6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependent_profiles',
    sa.Column('dependent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('care_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dependent_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_dependent_profiles_dependent_id'), 'dependent_profiles', ['dependent_id'], unique=False)
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    op.drop_index(op.f('ix_dependent_profiles_dependent_id'), table_name='dependent_profiles')
    op.drop_table('dependent_profiles')
    # ### end Alembic commands ###
