"""Added Chatbot History Table

Revision ID: 47cb16d3be6a
Revises: 933593397d03
Create Date: 2026-03-19 20:32:38.751159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cb16d3be6a'
down_revision: Union[str, Sequence[str], None] = '933593397d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_history',
    sa.Column('chatbot_history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.Enum('caregiver', 'dependent', name='user_role_enum'), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('ai_response_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chatbot_history_id')
    )
    op.create_index(op.f('ix_chatbot_history_chatbot_history_id'), 'chatbot_history', ['chatbot_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_history_chatbot_history_id'), table_name='chatbot_history')
    op.drop_table('chatbot_history')
    # ### end Alembic commands ###
