"""create care space module tables

Revision ID: 5025a6467194
Revises: 45942317238b
Create Date: 2026-03-01 19:22:43.941248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5025a6467194'
down_revision: Union[str, Sequence[str], None] = '42706df5ad40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_spaces',
    sa.Column('care_space_id', sa.Integer(), nullable=False),
    sa.Column('care_space_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('care_space_id')
    )
    op.create_index(op.f('ix_care_spaces_care_space_code'), 'care_spaces', ['care_space_code'], unique=True)
    op.create_index(op.f('ix_care_spaces_care_space_id'), 'care_spaces', ['care_space_id'], unique=False)
    op.create_table('care_space_dependents',
    sa.Column('care_space_dependent_id', sa.Integer(), nullable=False),
    sa.Column('care_space_id', sa.Integer(), nullable=False),
    sa.Column('dependent_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['care_space_id'], ['care_spaces.care_space_id'], ),
    sa.ForeignKeyConstraint(['dependent_id'], ['dependent_profiles.dependent_id'], ),
    sa.PrimaryKeyConstraint('care_space_dependent_id')
    )
    op.create_index(op.f('ix_care_space_dependents_care_space_dependent_id'), 'care_space_dependents', ['care_space_dependent_id'], unique=False)
    op.create_table('care_space_members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('care_space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_space', sa.Enum('owner', 'editor', 'viewer', name='role_in_space_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['care_space_id'], ['care_spaces.care_space_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_care_space_members_member_id'), 'care_space_members', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_space_members_member_id'), table_name='care_space_members')
    op.drop_table('care_space_members')
    op.drop_index(op.f('ix_care_space_dependents_care_space_dependent_id'), table_name='care_space_dependents')
    op.drop_table('care_space_dependents')
    op.drop_index(op.f('ix_care_spaces_care_space_id'), table_name='care_spaces')
    op.drop_index(op.f('ix_care_spaces_care_space_code'), table_name='care_spaces')
    op.drop_table('care_spaces')
    # ### end Alembic commands ###
