"""Added Care Space Join Code Table

Revision ID: 5c7a498478d0
Revises: ab826a8ef2cb
Create Date: 2026-03-07 23:10:36.392994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7a498478d0'
down_revision: Union[str, Sequence[str], None] = 'ab826a8ef2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_space_join_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('care_space_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='role_in_space_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['care_space_id'], ['care_spaces.care_space_id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_care_space_join_codes_code'), 'care_space_join_codes', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_space_join_codes_code'), table_name='care_space_join_codes')
    op.drop_table('care_space_join_codes')
    # ### end Alembic commands ###
