"""Merged Care Space Permission Tables

Revision ID: ab826a8ef2cb
Revises: 4e445ffc623f
Create Date: 2026-03-07 19:06:23.989773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab826a8ef2cb'
down_revision: Union[str, Sequence[str], None] = '4e445ffc623f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_space_members', 'can_manage_care_space')
    op.drop_column('care_space_members', 'can_manage_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_space_members', sa.Column('can_manage_tasks', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('care_space_members', sa.Column('can_manage_care_space', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
