"""Add user status, add care_space_member_permissions, merge care_space_dependents

Revision ID: bfa4f82c7bd4
Revises: e856e6dd8186
Create Date: 2026-03-07 03:01:10.854574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfa4f82c7bd4'
down_revision: Union[str, Sequence[str], None] = 'e856e6dd8186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_space_member_permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('care_space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_create_tasks', sa.Boolean(), nullable=False),
    sa.Column('can_edit_tasks', sa.Boolean(), nullable=False),
    sa.Column('can_delete_tasks', sa.Boolean(), nullable=False),
    sa.Column('can_assign_tasks', sa.Boolean(), nullable=False),
    sa.Column('can_add_members', sa.Boolean(), nullable=False),
    sa.Column('can_remove_members', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_space_id'], ['care_spaces.care_space_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_care_space_member_permissions_permission_id'), 'care_space_member_permissions', ['permission_id'], unique=False)
    op.drop_index(op.f('ix_care_space_dependents_care_space_dependent_id'), table_name='care_space_dependents')
    op.drop_table('care_space_dependents')
    op.add_column('care_spaces', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the care space code expires; null if permanent'))
    op.alter_column('care_spaces', 'care_space_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('care_spaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_care_spaces_expires_at'), 'care_spaces', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_spaces_expires_at'), table_name='care_spaces')
    op.alter_column('care_spaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('care_spaces', 'care_space_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('care_spaces', 'expires_at')
    op.create_table('care_space_dependents',
    sa.Column('care_space_dependent_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('care_space_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('removed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['care_space_id'], ['care_spaces.care_space_id'], name=op.f('care_space_dependents_care_space_id_fkey')),
    sa.ForeignKeyConstraint(['dependent_id'], ['dependent_profiles.dependent_id'], name=op.f('care_space_dependents_dependent_id_fkey')),
    sa.PrimaryKeyConstraint('care_space_dependent_id', name=op.f('care_space_dependents_pkey'))
    )
    op.create_index(op.f('ix_care_space_dependents_care_space_dependent_id'), 'care_space_dependents', ['care_space_dependent_id'], unique=False)
    op.drop_index(op.f('ix_care_space_member_permissions_permission_id'), table_name='care_space_member_permissions')
    op.drop_table('care_space_member_permissions')
    # ### end Alembic commands ###
