"""Fixed User role in Chatbot History

Revision ID: e04fa3d98ae7
Revises: 47cb16d3be6a
Create Date: 2026-03-19 21:25:54.583121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e04fa3d98ae7'
down_revision: Union[str, Sequence[str], None] = '47cb16d3be6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_history', 'user_role',
               existing_type=postgresql.ENUM('caregiver', 'dependent', name='user_role_enum'),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_history', 'user_role',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('caregiver', 'dependent', name='user_role_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
