# models/chatbot_history.py

"""
This module defines the ChatbotHistory ORM model for SQLAlchemy.

A ChatbotHistory record represents one interaction between a user and the AI.

Fields:
- chatbot_history_id: Primary key
- user_id: Foreign key to users.user_id
- user_role: Enum ('caregiver','dependent')
- query_text: Text sent by user
- ai_response_text: Text returned by AI
- created_at: Timestamp of the interaction
"""

# ---------------------------
# Standard Library Imports
# ---------------------------
from datetime import datetime, timezone

# ---------------------------
# SQLAlchemy Imports
# ---------------------------
from sqlalchemy import Column, Integer, Text, DateTime, ForeignKey, Enum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

# ---------------------------
# Local App Imports
# ---------------------------
from app.core.database import Base


# ---------------------------s
# ChatbotHistory Model
# ---------------------------
class ChatbotHistory(Base):
    """
    SQLAlchemy model representing an AI interaction with a user.
    """

    __tablename__ = "chatbot_history"

    # ---------------------------
    # Columns
    # ---------------------------
    chatbot_history_id = Column(
        Integer,
        primary_key=True,
        index=True,
        doc="Primary key for AI interaction"
    )

    user_id = Column(
        Integer,
        ForeignKey("users.user_id"),
        nullable=False,
        doc="User ID of the person interacting with the AI"
    )

    user_role = Column(
        Text,
        nullable=False,
        doc="Role of the user at time of interaction"
    )

    query_text = Column(
        Text,
        nullable=False,
        doc="Text sent by the user to the AI"
    )

    ai_response_text = Column(
        Text,
        nullable=False,
        doc="Response generated by the AI"
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Timestamp when the interaction was created"
    )

    # ---------------------------
    # Relationships
    # ---------------------------
    user = relationship(
        "User",
        back_populates="chatbot_history",
        doc="Relationship to the user who made the interaction"
    )