# repositories/chatbot_history.py

"""
Repository for managing ChatbotHistory interactions in the database.

Supports:
- Creating new history records
- Listing interactions by user
"""

# ---------------------------
# Standard Library Imports
# ---------------------------
from datetime import datetime, timezone

# ---------------------------
# SQLAlchemy Imports
# ---------------------------
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

# ---------------------------
# Local App Imports
# ---------------------------
from app.models.chatbot_history import ChatbotHistory
from app.schemas.chatbot import ChatbotHistoryCreate


# ---------------------------
# ChatbotHistory Repository
# ---------------------------
class ChatbotHistorysRepository:
    """
    Repository for managing ChatbotHistory database operations.
    """
    def __init__(self, db: AsyncSession):
        self.db = db

    # ---------------------------
    # CREATE
    # ---------------------------
    async def create(self, history_data: ChatbotHistoryCreate) -> ChatbotHistory:
        """
        Create a new chatbot history record.
        """
        history = ChatbotHistory(
            user_id=history_data.user_id,
            user_role=history_data.user_role.value if hasattr(history_data.user_role, "value") else history_data.user_role,
            query_text=history_data.query_text,
            ai_response_text=history_data.ai_response_text,
        )
        self.db.add(history)
        await self.db.commit()
        await self.db.refresh(history)  # refresh to get autogenerated ID
        return history

    # ---------------------------
    # LIST / READ
    # ---------------------------
    async def list_by_user(self, user_id: int, limit: int | None = None) -> list[ChatbotHistory]:
        query = select(ChatbotHistory).where(ChatbotHistory.user_id == user_id).order_by(ChatbotHistory.created_at.desc())
        if limit:
            query = query.limit(limit)
        result = await self.db.execute(query)
        return result.scalars().all()
    
    # ---------------------------
    # OPTIONAL: Get by ID
    # ---------------------------
    async def get_by_id(self, history_id: int) -> ChatbotHistory | None:
        """
        Retrieve a single chatbot interaction by its ID.
        """
        result = await self.db.execute(
            select(ChatbotHistory).where(ChatbotHistory.chatbot_history_id == history_id)
        )
        return result.scalars().first()
    
    # ---------------------------
    # PAGINATED HISTORY
    # ---------------------------
    async def list_by_user_paginated(
        self,
        user_id: int,
        limit: int = 20,
        offset: int = 0
    ):
        result = await self.db.execute(
            select(ChatbotHistory)
            .where(ChatbotHistory.user_id == user_id)
            .order_by(ChatbotHistory.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        return result.scalars().all()